/-
Copyright (c) 2026 The pontryagin contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The pontryagin contributors
-/
import Mathlib.Analysis.Complex.Basic
import Mathlib.Topology.ContinuousMap.StoneWeierstrass
import Mathlib.Topology.ContinuousMap.ZeroAtInfty
import Mathlib.Topology.Compactification.OnePoint.Basic

/-!
# The Stone–Weierstrass theorem for functions vanishing at infinity

This file fills a gap in Mathlib (general-purpose material with no project-specific content)
and is a candidate for upstreaming; see `UPSTREAMING.md` for the audit and target locations.

Let `X` be a locally compact Hausdorff space and `𝕜` be either `ℝ` or `ℂ`.  This file proves the
non-unital version of the Stone–Weierstrass theorem: a non-unital star subalgebra `A` of
`C₀(X, 𝕜)`, the continuous functions on `X` vanishing at infinity, is dense provided that it
separates the points of `X` and vanishes nowhere (that is, for every `x : X` there is some
`f ∈ A` with `f x ≠ 0`).

The proof passes through the one-point compactification `OnePoint X`.  Functions vanishing at
infinity extend by `0` to continuous functions on `OnePoint X`, isometrically identifying
`C₀(X, 𝕜)` with the (closed) kernel of the evaluation map at the point `∞`.  The unital star
subalgebra of `C(OnePoint X, 𝕜)` generated by the image of `A` separates the points of
`OnePoint X` (the nowhere-vanishing hypothesis separates points of `X` from `∞`), hence is dense
by the compact Stone–Weierstrass theorem, and intersecting with the kernel of evaluation at `∞`
recovers the density of `A`.

## Main definitions

* `ZeroAtInftyContinuousMap.toContinuousMapOnePoint`: the extension of `f : C₀(X, β)` to a
  continuous map on `OnePoint X` taking the value `0` at `∞`.
* `ZeroAtInftyContinuousMap.toContinuousMapOnePointHom`: the extension map bundled as a
  non-unital star algebra homomorphism `C₀(X, 𝕜) →⋆ₙₐ[𝕜] C(OnePoint X, 𝕜)`.

## Main statements

* `ZeroAtInftyContinuousMap.nonUnitalStarSubalgebra_dense_of_separatesPoints`: a non-unital star
  subalgebra of `C₀(X, 𝕜)` which separates points and vanishes nowhere is dense.
* `ZeroAtInftyContinuousMap.nonUnitalStarSubalgebra_topologicalClosure_eq_top_of_separatesPoints`:
  the same statement, phrased as `A.topologicalClosure = ⊤`.
-/

noncomputable section

open Filter Topology OnePoint

open scoped ZeroAtInfty

namespace ZeroAtInftyContinuousMap

section OnePointExtension

variable {X : Type*} [TopologicalSpace X] [R1Space X]

section Zero

variable {β : Type*} [TopologicalSpace β] [Zero β]

/-- The extension of `f : C₀(X, β)` to the one-point compactification of `X`, taking the value
`0` at the point `∞`. -/
def toContinuousMapOnePoint (f : C₀(X, β)) : C(OnePoint X, β) :=
  OnePoint.continuousMapMk f.toContinuousMap 0 <| by
    rw [coclosedCompact_eq_cocompact]
    exact zero_at_infty f

@[simp]
theorem toContinuousMapOnePoint_apply_coe (f : C₀(X, β)) (x : X) :
    toContinuousMapOnePoint f (x : OnePoint X) = f x :=
  rfl

@[simp]
theorem toContinuousMapOnePoint_apply_infty (f : C₀(X, β)) :
    toContinuousMapOnePoint f ∞ = 0 :=
  rfl

end Zero

/-- Extension to the one-point compactification is an isometry, since the extension takes the
value `0` at `∞`. -/
theorem isometry_toContinuousMapOnePoint {β : Type*} [PseudoMetricSpace β] [Zero β] :
    Isometry (toContinuousMapOnePoint : C₀(X, β) → C(OnePoint X, β)) := by
  refine Isometry.of_dist_eq fun f g =>
    le_antisymm ((ContinuousMap.dist_le dist_nonneg).mpr fun p => ?_) ?_
  · induction p using OnePoint.rec with
    | infty => simp
    | coe x =>
      calc dist (toContinuousMapOnePoint f x) (toContinuousMapOnePoint g x)
          = dist (f.toBCF x) (g.toBCF x) := rfl
        _ ≤ dist f.toBCF g.toBCF := BoundedContinuousFunction.dist_coe_le_dist x
        _ = dist f g := dist_toBCF_eq_dist
  · rw [← dist_toBCF_eq_dist]
    refine (BoundedContinuousFunction.dist_le dist_nonneg).mpr fun x => ?_
    calc dist (f.toBCF x) (g.toBCF x)
        = dist (toContinuousMapOnePoint f (x : OnePoint X))
            (toContinuousMapOnePoint g (x : OnePoint X)) := rfl
      _ ≤ dist (toContinuousMapOnePoint f) (toContinuousMapOnePoint g) :=
          ContinuousMap.dist_apply_le_dist _

variable (𝕜 : Type*) [RCLike 𝕜]

/-- Extension to the one-point compactification, as a non-unital star algebra homomorphism from
`C₀(X, 𝕜)` to `C(OnePoint X, 𝕜)`. -/
def toContinuousMapOnePointHom : C₀(X, 𝕜) →⋆ₙₐ[𝕜] C(OnePoint X, 𝕜) where
  toFun := toContinuousMapOnePoint
  map_smul' r f := by ext p; induction p using OnePoint.rec <;> simp
  map_zero' := by ext p; induction p using OnePoint.rec <;> simp
  map_add' f g := by ext p; induction p using OnePoint.rec <;> simp
  map_mul' f g := by ext p; induction p using OnePoint.rec <;> simp
  map_star' f := by ext p; induction p using OnePoint.rec <;> simp

@[simp]
theorem coe_toContinuousMapOnePointHom :
    ⇑(toContinuousMapOnePointHom 𝕜 : C₀(X, 𝕜) →⋆ₙₐ[𝕜] C(OnePoint X, 𝕜)) =
      toContinuousMapOnePoint :=
  rfl

end OnePointExtension

section StoneWeierstrass

variable {X : Type*} [TopologicalSpace X] [LocallyCompactSpace X] [T2Space X]
variable {𝕜 : Type*} [RCLike 𝕜]

/-- **Stone–Weierstrass theorem for functions vanishing at infinity**: a non-unital star
subalgebra `A` of `C₀(X, 𝕜)`, where `X` is a locally compact Hausdorff space and `𝕜` is either
`ℝ` or `ℂ`, is dense if it separates points and vanishes nowhere. -/
theorem nonUnitalStarSubalgebra_dense_of_separatesPoints
    (A : NonUnitalStarSubalgebra 𝕜 C₀(X, 𝕜))
    (hsep : ∀ x y : X, x ≠ y → ∃ f ∈ A, f x ≠ f y)
    (hnz : ∀ x : X, ∃ f ∈ A, f x ≠ 0) :
    Dense (A : Set C₀(X, 𝕜)) := by
  -- `M` is the image of `A` in `C(OnePoint X, 𝕜)` under extension by `0` at `∞`, and `B` is the
  -- unital star subalgebra it generates; `φ` is evaluation at `∞`.
  set M : NonUnitalStarSubalgebra 𝕜 C(OnePoint X, 𝕜) := A.map (toContinuousMapOnePointHom 𝕜)
    with hM
  set B : StarSubalgebra 𝕜 C(OnePoint X, 𝕜) := StarAlgebra.adjoin 𝕜 (M : Set C(OnePoint X, 𝕜))
    with hB
  set φ : C(OnePoint X, 𝕜) →⋆ₐ[𝕜] 𝕜 := ContinuousMap.evalStarAlgHom 𝕜 𝕜 (∞ : OnePoint X)
    with hφ
  -- Every element of `M` vanishes at `∞`.
  have hM0 : ∀ g ∈ M, g ∞ = 0 := by
    intro g hg
    obtain ⟨f, -, rfl⟩ := NonUnitalStarSubalgebra.mem_map.mp hg
    simp
  have hMB : (M : Set C(OnePoint X, 𝕜)) ⊆ B := StarAlgebra.subset_adjoin 𝕜 _
  have hΦA : ∀ f ∈ A, toContinuousMapOnePoint f ∈ M := fun f hf =>
    NonUnitalStarSubalgebra.mem_map.mpr ⟨f, hf, rfl⟩
  -- `B` separates the points of `OnePoint X`: points of `X` are separated by `A`, and the
  -- nowhere-vanishing hypothesis separates points of `X` from `∞`.
  have hBsep : B.SeparatesPoints := by
    intro p q hpq
    induction p using OnePoint.rec with
    | infty =>
      induction q using OnePoint.rec with
      | infty => exact absurd rfl hpq
      | coe y =>
        obtain ⟨f, hfA, hfy⟩ := hnz y
        exact ⟨_, ⟨_, hMB (hΦA f hfA), rfl⟩, by simpa using Ne.symm hfy⟩
    | coe x =>
      induction q using OnePoint.rec with
      | infty =>
        obtain ⟨f, hfA, hfx⟩ := hnz x
        exact ⟨_, ⟨_, hMB (hΦA f hfA), rfl⟩, by simpa using hfx⟩
      | coe y =>
        obtain ⟨f, hfA, hfxy⟩ := hsep x y (by simpa using hpq)
        exact ⟨_, ⟨_, hMB (hΦA f hfA), rfl⟩, by simpa using hfxy⟩
  -- Hence `B` is dense, by the compact Stone-Weierstrass theorem.
  have hBdense : closure (B : Set C(OnePoint X, 𝕜)) = Set.univ := by
    rw [← StarSubalgebra.topologicalClosure_coe,
      ContinuousMap.starSubalgebra_topologicalClosure_eq_top_of_separatesPoints B hBsep,
      StarSubalgebra.coe_top]
  -- Intersecting `B` with the kernel of the evaluation at `∞` recovers `M`, since an element
  -- of `B` is the sum of an element of `M` and a constant.
  have hBM : (B : Set C(OnePoint X, 𝕜)) ∩ RingHom.ker φ = (M : Set C(OnePoint X, 𝕜)) := by
    ext g
    constructor
    · rintro ⟨hgB, hgφ⟩
      rw [SetLike.mem_coe, ← StarSubalgebra.mem_toSubalgebra, ← Subalgebra.mem_toSubmodule,
        hB, StarAlgebra.adjoin_nonUnitalStarSubalgebra_eq_span, Submodule.mem_sup] at hgB
      obtain ⟨u, hu, m, hm, rfl⟩ := hgB
      obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.mp hu
      rw [SetLike.mem_coe, RingHom.mem_ker, hφ] at hgφ
      rw [NonUnitalSubalgebra.mem_toSubmodule] at hm
      have hc : c = 0 := by simpa [hM0 m hm] using hgφ
      simpa [hc] using hm
    · intro hg
      refine ⟨hMB hg, ?_⟩
      rw [SetLike.mem_coe, RingHom.mem_ker, hφ]
      simpa using hM0 g hg
  -- Therefore the closure of `M` is exactly the kernel of the evaluation at `∞`.
  have hMker : closure (M : Set C(OnePoint X, 𝕜)) = (RingHom.ker φ : Set C(OnePoint X, 𝕜)) := by
    rw [← hBM, ContinuousMap.AlgHom.closure_ker_inter φ (continuous_eval_const _) B,
      hBdense, Set.univ_inter]
  -- Finally, pull everything back along the isometric embedding `C₀(X, 𝕜) → C(OnePoint X, 𝕜)`.
  have hemb : IsEmbedding (toContinuousMapOnePoint : C₀(X, 𝕜) → C(OnePoint X, 𝕜)) :=
    isometry_toContinuousMapOnePoint.isEmbedding
  rw [dense_iff_closure_eq, hemb.closure_eq_preimage_closure_image]
  have himage : toContinuousMapOnePoint '' (A : Set C₀(X, 𝕜)) = (M : Set C(OnePoint X, 𝕜)) := by
    rw [hM, NonUnitalStarSubalgebra.coe_map, coe_toContinuousMapOnePointHom]
  rw [himage, hMker]
  exact Set.eq_univ_of_forall fun f => by
    simp [RingHom.mem_ker, hφ]

/-- **Stone–Weierstrass theorem for functions vanishing at infinity**: a non-unital star
subalgebra `A` of `C₀(X, 𝕜)`, where `X` is a locally compact Hausdorff space and `𝕜` is either
`ℝ` or `ℂ`, has full topological closure if it separates points and vanishes nowhere. -/
theorem nonUnitalStarSubalgebra_topologicalClosure_eq_top_of_separatesPoints
    (A : NonUnitalStarSubalgebra 𝕜 C₀(X, 𝕜))
    (hsep : ∀ x y : X, x ≠ y → ∃ f ∈ A, f x ≠ f y)
    (hnz : ∀ x : X, ∃ f ∈ A, f x ≠ 0) :
    A.topologicalClosure = ⊤ :=
  SetLike.ext' <|
    (nonUnitalStarSubalgebra_dense_of_separatesPoints A hsep hnz).closure_eq

end StoneWeierstrass

end ZeroAtInftyContinuousMap
